### ISSUE TITLE
powerline:setup gives an error

### ISSUE THREAD

**Issue by deathtrip** [muesli/elvish-libs#13]
I added `use github.com/muesli/elvish-libs/theme/powerline` and  `powerline:setup` to ~/.elvish/rc.elv , and when i start elvish i get:
`Exception: variable $powerline:setup~ not found`

**Comment by muesli** [comment]
I don't think there's a `setup` method to call. All I do in my `rc.elv` is:

```
# Prompt
use github.com/muesli/elvish-libs/theme/powerline
edit:prompt-stale-transform = [x]{ put $x }
edit:rprompt-stale-transform = [x]{ put $x }
```

**Comment by hexsel** [comment]
Like deathtrip, I was following the instructions on https://github.com/muesli/elvish-libs/blob/master/theme/powerline.elv#L13. I also tried the syntax you suggested, but I guess that's no longer supported?

Following the instruction on the README worked though.

**Comment by muesli** [comment]
Ah, thanks for the heads up, the source comment is indeed outdated by now. All you should need to do is add the above mentioned stuff to your `rc.elv`.

**Comment by muesli** [comment]
Fixed.

**Comment by erwin** [comment]
I'm getting `compilation error: variable $x not found`.  I'm on:

```
❯ elvish -version 
0.18.0
```

With the following in my `rc.elv`:

```
use github.com/muesli/elvish-libs/theme/powerline
edit:prompt-stale-transform = [x]{ put $x }
edit:rprompt-stale-transform = [x]{ put $x }
```

I'm getting:

```
compilation error: variable $x not found
elvish/rc.elv, line 4: edit:prompt-stale-transform = [x]{ put $x }
```

**Comment by muesli** [comment]
Try:

```
set edit:prompt-stale-transform = {|x| put $x }
set edit:rprompt-stale-transform = {|x| put $x }
```

**Comment by erwin** [comment]
Awesome. That works. And you've already updated the README.md.

Looks very cool. Been wanting an alternative to two decades of accreted `zsh` config and looks like this may be it!

I wanted to like `fish` but it didn't have the features to replace `zsh` for me.
